### ISSUE TITLE
Review of your release

### ISSUE THREAD

**Issue by jimeUWOshkosh** [ddmitov/camel-doctor#1]
Halo
Tried to leave a comment at blog,perl.org but Moveable Type would not let me create an account.

Using Ubuntu 16.04, Perl v5.22.1. Using "Pro Perl Debugging": Chap3
Chrome v57.0.2987.98  and Firefox v52.0

1) Would be nice if the cursor stayed in the input field
2) Some of the STDOUT is not display like it is in the perl debugger

So you don't have to purchase the book (source and input file)
cameldoc charcount walrus
github.com/Apress/pro-perl-debugging/tree/master/1590594541-1/Chapter03

Here is the saved debugger history for the first couple of pages of Chapter03 to show you
the STDOUT difference. (see attachment)
[debug.txt](https://github.com/ddmitov/camel-doctor/files/834577/debug.txt)

**Comment by ddmitov** [comment]
Hi jimeUWOshkosh and thank you for your feedback!

The formatting of the debugger output is controlled by
'{camel_doctor_binary_directory}/resources/dbgformatter.pl'.
Debugger output is not displayed in its raw form by design because of four reasons:
1. Features like editor support or 'man perldebug' are not supported inside Camel Doctor and
    all refernces to them are useless.
2. Terminal characters disrupt HTML formatting and have to be removed.
3. Newlines have to be transformed to <br> tags for a proper HTML rendering.
4. HTML output from a debugged script has to be properly escaped.

But after reading your comment, I removed two debugger output formatting problems in my last commit:
1. Debugger command prompt is not removed anymore.
    It was removed because user can not enter any command after the prompt,
    but the command numbering is important and now I think it has to stay.
2. Repeated line number after the line info section is removed and now
    the first line of the debugger output in Camel Doctor is identical to
    the first line of debugger output in terminal.
    I am still puzzled why this repeated line number appeared in the output.

Using the 'charcount' script from Chapter 3 of "Pro Perl Debugging" I tested in parallel
the debugger output in Camel Doctor and in terminal and I saw no difference after the updates I made.
I am also using Ubuntu 16.04 and Perl v5.22.1 (perl5db.pl version 1.49).
Your saved debugger history was handy for my tests.

The input field has now the 'autofocus' HTML5 option and
the cursor is always ready to accept commands.

I didn't use "Pro Perl Debugging" in my tests until now, but the book seems very useful and in-depth.
Thank you for the link to the example scripts!

If you have any other feedback or suggestions, do not hesitate to write!

With all my best wishes,
Dimitar D. Mitov
